# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjetoeArquitetura' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjetoeArquitetura

pod 'Alamofire', '~> 4.7'
pod 'ObjectMapper', '~> 3.3'
pod 'AlamofireObjectMapper', '= 5.2.1'
pod 'PKHUD'

  target 'ProjetoeArquiteturaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjetoeArquiteturaUITests' do
    # Pods for testing
  end

end
